package com.xiechao.pojo;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.project
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.time
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.route
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private String route;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.distance
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private Integer distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.licences
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private String licences;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.weight
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.others
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    private String others;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.project
     *
     * @return the value of item.project
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.project
     *
     * @param project the value for item.project
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.time
     *
     * @return the value of item.time
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.time
     *
     * @param time the value for item.time
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.route
     *
     * @return the value of item.route
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.route
     *
     * @param route the value for item.route
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.distance
     *
     * @return the value of item.distance
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public Integer getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.distance
     *
     * @param distance the value for item.distance
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.licences
     *
     * @return the value of item.licences
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public String getLicences() {
        return licences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.licences
     *
     * @param licences the value for item.licences
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setLicences(String licences) {
        this.licences = licences == null ? null : licences.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.weight
     *
     * @return the value of item.weight
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.weight
     *
     * @param weight the value for item.weight
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.others
     *
     * @return the value of item.others
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public String getOthers() {
        return others;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.others
     *
     * @param others the value for item.others
     *
     * @mbggenerated Sun Apr 15 16:02:41 CST 2018
     */
    public void setOthers(String others) {
        this.others = others == null ? null : others.trim();
    }
}